### ISSUE TITLE
Provide support for additional input file formats in PointStatWrapper

### ISSUE THREAD

**Issue by bikegeek** [NCAR/METplus#106]
Perry Shafran has submitted a MET Helpdesk ticket for numerous gridded forecast files (NAM, HRRR, etc.) which aren't currently supported in the PointStatWrapper, as it was originally implemented to support the data provided for the CROW sprint.

Specifically, allow the user to have the forecast hour embedded in the filename and separate the data into dated subdirectories.

**Comment by jprestop** [comment]
Tasks:

- Create generic function in met_util.py to extract a date from a dated directory or file
- In point_stat, utilize this new function
- In point_stat, change InputFileInfo tuple, changing cycle_or_fcst to separate cycle and fcst because it is possible to have both
- Update unit tests for point_stat and include this new functionality
- Pull code from get_pb_files_by_time in pb2nc_wrapper.py to use new code in met_util.py
- Possibly update unit tests for pb2nc (if necessary based on pull out of code from get_pb_files_by_time)

**Comment by bikegeek** [comment]
Perry's examples now work.  Closing.
