### ISSUE TITLE
A new METplus user_env_vars section in conf file

### ISSUE THREAD

**Issue by jimfrimel** [NCAR/METplus#141]
The following had been discussed with the group at the 2018 Nov 1 
METplus meeting, and this issue was a result of that discussion.

The team decided the capability described below in the 'Background:',
section would be nice to have and we should make it available to all use cases. 

Requirement:
This needs to be implemented in such a way that is maintained and added in one
object and not duplicated across all the modules.

Background:
A new "un-broadcasted"  feature added and unique to the ensemble stat wrapper 
is the ability for the user to define environment variables that are automatically 
exported and added to the runtime environment when MET is called from METplus,
as described below.

```
# TODO: jtf This is beta functionality, it has been tested but
# is only available in the ensemble stat modules.

# NOTE:
# All variables in the user_env_vars section will be exported.
# The [user_env_vars section] is not required,
# or it can, and be empty.

[user_env_vars]
# user_env_vars section:
# Use this section to define new environment variables that you would
# like exported to the runtime environment, where they can be accessed
# and used by MET.  They can be named as you wish.
# This is really just a convenience so any new
# environment variables you may want to be defined can be maintained
# in this conf file. rather than putting them in your login shell.
#
SOMENEW_ENVVAR=some_new_value
```

**Comment by jimfrimel** [comment]
FYI ... 
Here is the current implementation in the ensemble stat use case. 

The variables are being added with the commabd_builder.add_env_var method.

In addition to adding it to the function in command builder .... 
the following functionality would ideally be encapsulated...
 .... The following was necessary in the ensemble stat wrapper ... and would be in
every wrapper that matter, since they are all "patterned" the same .... However,
we want to avoid doing so ... else we are just duplicating code ...


**The additional functionality to consider and encapsulate is that each conf variable
 used by each use case is added to each objects local dictionary**

```
        # We add a user_env_vars section to the conf object if it does not exist.
        # Doing so simplifies the use of  user_env_vars in the code
        # since you will not have to check for the existence of the section
        # with each reference, at the very least it will
        # be an empty list [] and any for loops will not be entered.
        if 'user_env_vars' not in self.p.sections():
            self.p.add_section('user_env_vars')
        for env_var in self.p.keys('user_env_vars'):
            ce_dict[env_var]=self.p.getstr('user_env_vars',env_var,'')

        #Add any user_env_vars environment variables.
        for env_var in self.p.keys('user_env_vars'):
            self.add_env_var(env_var, self.ce_dict[env_var])
```

**We don't want to have to define each environment variable in each
wrapper that we need to export and print ... this should be encapsulated also. 
Additionally we should iterate all the valid variables that are being used without
having to define a special case for env variables that a user may or may not define,
ie, in this case it is the MET_OBS_ERROR_TABLE. That is we don't want to print
env vars that are not being used.**
```
        self.logger.debug("ENVIRONMENT FOR NEXT COMMAND: ")
        for env_var in self.p.keys('user_env_vars'):
            self.print_env_item(env_var)

        self.logger.debug("COPYABLE ENVIRONMENT FOR NEXT COMMAND: ")

        if met_obs_error_table:
            self.print_env_copy(self.p.keys('user_env_vars') +
                                ["MET_OBS_ERROR_TABLE", "MODEL",
                                 "FCST_VAR", "OBS_VAR", "LEVEL",
                                 "OBTYPE", "CONFIG_DIR",
                                 "FCST_FIELD", "OBS_FIELD",
                                 "INPUT_BASE", "FCST_LEAD",
                                 "OBS_WINDOW_BEGIN", "OBS_WINDOW_END"])
        else:
            self.print_env_copy(self.p.keys('user_env_vars') +
                                ["MODEL", "FCST_VAR", "OBS_VAR",
                                 "LEVEL", "OBTYPE", "CONFIG_DIR",
                                 "FCST_FIELD", "OBS_FIELD",
                                 "INPUT_BASE", "FCST_LEAD",
                                 "OBS_WINDOW_BEGIN", "OBS_WINDOW_END"])
```

**Comment by jimfrimel** [comment]
Additionally,  

Hank had mentioned it would be good to make sure we are not
accidentally stepping on an existing environment variable by some chance if it is already
being used ... or already defined in the user environment ... 

I think he mentioned that ... should probably as Hank again....

**Comment by georgemccabe** [comment]
Thanks for the info, Jim. That code looks good and could be added and called within CommandBuilder so that all wrappers execute it.

1) I see you add each item to the local wrapper dictionary. Is that necessary? I think if a conf item is required by the wrapper, it does not belong in the user_env_vars section of the conf. I feel that it is sufficient to add the variable to the environment. It can be referenced directly from self.p if you may need to reference it in the code. I am open to discussion about this...

2) Regarding printing the user defined environment variables in a wrapper, we can add the printing of these variables inside print_env_copy directly so we don't need to specify it in the call. As far as printing it outside of that, I am not sure of a generalized way to add that except to add the loop and print_env_items call to a function that can be called so that it only takes 1 line instead of 2.

3) Hank, do you mean we should be aware if that variable has already been set in the environment so that we don't overwrite the user's environment? If so, we can handle that by either adding a warning statement saying that the variable has been overwritten by METplus, or we can error out and require the user to unset the variable in either their environment or in the conf. At first thought I am leaning towards the former since the user may be intentionally doing that, but we should still let them know that it is happening in the logs.

**Comment by georgemccabe** [comment]
Update:
1) I modified CommandBuilder so that each wrapper that gets initialized will set the user defined environment variables automatically. 

2) I added a function in CommandBuilder to print all user defined environment variables called print_user_env_items(). This can be called within the individual wrappers if the user wants to output these variables.

3) I modified CommandBuilder's print_env_copy(..) function to add the export statements for each user defined variable so you don't need to add them to the list that is passed to the function. I can remove this if we would prefer to set this on a wrapper by wrapper basis.

4) I added then removed code to check if a user defined variable is already set in the environment and warn if it is. The problem here is we add environment variables to os.environ as well as the local self.env. The first wrapper called will not report a warning, but each wrapper following the first in the process list will give a warning since the variable has already been added to the environment. A work around would be to set the user environment variables once before we run each wrapper so that the environment is set across the board.

**Comment by georgemccabe** [comment]
Also, I removed the code where the user variables get added to the dictionary because different wrappers have different names for the dictionaries. We may want to reconcile this so that each wrapper has the same variable name for the dictionary.

**Comment by georgemccabe** [comment]
I just merged these changes into the develop branch. We can revisit the environment checking if we need to. The code to check is currently commented out. To fix this, we will have to remove the call to modify os.environ when we set a new environment variable and instead pass in the self.env environment to the produtil exe call.
