### ISSUE TITLE
Refactor point_stat and pb2nc wrappers to utilize METplus time looping

### ISSUE THREAD

**Issue by georgemccabe** [NCAR/METplus#201]

**Comment by georgemccabe** [comment]
#191 and #110 are related to this work.

**Comment by georgemccabe** [comment]
#102 , #103 , #104 , and #105 may also be related (pb2nc issues)

**Comment by malloryprow** [comment]
Some of the file formats that have been cause Perry problems. Some we were able to get fixes for, but want to make sure rework works for these past issues

**PB2NC**

- /com/hourly/prod/hourly.20190320/aqm.t12z.prepbufr.tm00 (not getting the directory structure right in pb2nc)

- /com2/nam/prod/nam.20190217/nam.t00z.prepbufr.tm00, /com2/nam/prod/nam.20190217/nam.t00z.prepbufr.tm00.nr and /com2/nam/prod/nam.20190217/nam.t06z.prepbufr.tm06 (pb2nc was being run though these files are valid at the same time (tm06 preferred and don't want to use the .nr) this was fixed by changing the prepbufr file regex, PREPBUFR_FILE_REGEX = .*nam.t([0-9]{2})z.prepbufr.tm([0-9]{1})([1-9]{1})$ )

**POINT_STAT**

- /com2/nam/prod/nam.20181112/nam.t00z.awphys63.tm00.grib2 (point_stat was matching up the files together correctly because the valid time wasn't being computed corrected, we added a line in the point_stat wrapper to fix this)

- no verification for any valid times 18 to 23Z on a given day, this is probably because of the pb2nc output format ex. prepbufr.nam.20190312.t00z.tm03.nc - valid time 21Z on 20190311. Fixed by using NC_FILE_TMPL = prepbufr.nam.{valid?fmt=%Y%m%d%H}.nc resulting in prepbufr.nam.2019031221.nc

**Comment by georgemccabe** [comment]
point_stat and pb2nc wrappers have been refactored to loop over run times and use filename_templates instead of regex to find files. All of the filename cases listed should be handled by these wrappers given that the config is set correctly.
