### ISSUE TITLE
Append timestamp to metplus_final.conf

### ISSUE THREAD

**Issue by NYColoraDan** [NCAR/METplus#64]
Because configurations can change run-to-run, it would be nice to append a timestamp with the run time in it to the metplus_final.conf (or have the option to). The functionality could be similar to the LOG_TIMESTAMP_TEMPLATE config option in metplus_logging.conf e.g.:

FINAL_CONF_TIMESTAMP_TEMPLATE

which then gets appended to the metplus_final.conf.

**Comment by georgemccabe** [comment]
I modified config_launcher.py to set an item in [config] called CLOCK_TIME which is set to the current run time formatted as %Y%m%d%H%M%S. This can be used to set the METPLUS_CONF variable to use the current time.

METPLUS_CONF={OUTPUT_BASE}/metplus_final.{CLOCK_TIME}.conf

This addition is also useful even if you don't use {CLOCK_TIME} in any config item, because the final conf file will now contain a timestamp of the run so it is easy to see when it was run.

If another timestamp is desired besides the current time, you can add another variable to METPLUS_CONF, such as INIT_BEG or VALID_BEG.
