### ISSUE TITLE
Allowing more than 2D in NetCDF files

### ISSUE THREAD

**Issue by CPKalb** [NCAR/METplus#95]
Modify the wrappers to allow up to 4 Dimensions in netCDF files.

**Comment by georgemccabe** [comment]
@JohnHalleyGotway  proposed that the grid_stat/mode/etc wrappers check if pcp_combine has been run on either forecast or observation files prior to that wrapper. If so, then the field name should be set to NAME_LEVEL, and the level should be set to (*,*) since that is what is generated by pcp_combine. If pcp_combine has not been run, it will use the user defined name/level where name is defined as NAME_LEVEL instead of just name, and level will can be specified as the NetCDF format with more than 2 dimensions, i.e. (0,0,*,*)

**Comment by georgemccabe** [comment]
I made the changes @JohnHalleyGotway  proposed and all of the tests passed. I tried to run a case that @CPKalb had provided me running Mode on NetCDF data with 4 dimensions. I was able to get her case to run via METplus. An issue I came across is [FCST/OBS]_VARn_LEVELS can take a list of levels. This capability doesn't allow you to specify a NetCDF level because it contains commas, i.e. (0,0,\*,\*). I had to modify the getlist function allow list items to contain commas if they are found inside quotes. I did this using the csv library's reader function. To specify NetCDF levels in a METplus conf file, you must use quotes to designate the level. For example:

FCST_VAR1_NAME = digitalVil
FCST_VAR1_LEVELS = "(0,0,\*,\*)", "(0,1,\*\*)"

This example will process two fields:

name = digitalVil, level = (0,0,\*,\*)
and
name = digitalVil, level = (0,1,\*,\*)

The change to getlist still removes white space and preserves the existing uses of the function. I added some pytests with a few uses (getlist, getlistint, getlistfloat, getlist with commas).
